### ISSUE TITLE
Can this script convert fMRI data to MNI152

### ISSUE THREAD

**Issue by Student-HXJ** [pykao/CT2MNI152#2]
Hi, I got fMRI data from HCP,  can I use this script to convert fMRI data to MNI152?

**Comment by unimusic** [comment]
I haven't tried it, but I think HCP already has fMRI in MNI152 space. Please let me know if I'm wrong about this.
![Screenshot_20190616-150907](https://user-images.githubusercontent.com/10647159/59570194-17ee0d00-9049-11e9-81ba-7152dcddabef.png)

**Comment by Student-HXJ** [comment]
Yeah, the data from preprocessed has already converted to MNI152. But not in unprocessed, so I want to find a way to solve it when I collect fMRI data by myself

**Comment by unimusic** [comment]
Oh, I see. I haven't tried it on fMRI but it should work with minor tweaks. However, you would need to do some other preprocessing steps (eddy, etc) before getting to the registration step.

**Comment by Student-HXJ** [comment]
Ok, thank you!
